version: '3'

services:
    postgres:
      container_name: postgres
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - "5432:5432"

    backend:
      image: golang:1.6.1-alpine
      build: ./backend
      env_file:
        - ./backend/config/app.env
      volumes:
        - .:/go/src/app
        - ./postgres/postgres:/var/lib/postgresql/data
      restart: unless-stopped
      depends_on:
        - postgres

